In [3]:
import pandas

In [3]:
import numpy as np
import pandas as pd

In [10]:
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [11]:
rng=np.random.RandomState(42)
ser=pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [13]:
df=pd.DataFrame(rng.randint(0,10,(3,4)), columns=["A","B","C","D"])       # 3*4 랜덤행렬
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [14]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

# UFuncs

In [16]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                             'California': 423967}, name='area')
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                                   'New York': 19651127}, name='population')

In [17]:
pop/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [18]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [22]:
A = pd.Series([2, 4, 6], index=[0, 1, 2]) 
B = pd.Series([1, 3, 5], index=[1, 2, 3]) 
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [23]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [25]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0   0  11
1  11  16

In [26]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  9  2  6
1  3  8  2
2  4  2  6

In [27]:
A+B

A     B   C
0   2.0  20.0 NaN
1  19.0  19.0 NaN
2   NaN   NaN NaN

In [31]:
# fill_value : missing entries 채우기.
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   2.0  20.0  15.5
1  19.0  19.0  11.5
2  11.5  13.5  15.5

In [37]:
A = rng.randint(10, size=(3, 4))       # DataFrame 형태가 아님.
A

array([[4, 8, 6, 1],
       [3, 8, 1, 9],
       [8, 9, 4, 1]])

In [40]:
A[0]

array([4, 8, 6, 1])

In [41]:
A-A[0]          # 첫 행의 값을 모든 원소에서 빼준다.

array([[ 0,  0,  0,  0],
       [-1,  0, -5,  8],
       [ 4,  1, -2,  0]])

In [44]:
df = pd.DataFrame(A, columns=list('QRST'))
df.iloc[0]

Q    4
R    8
S    6
T    1
Name: 0, dtype: int64

In [45]:
df

Q  R  S  T
0  4  8  6  1
1  3  8  1  9
2  8  9  4  1

In [46]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1  0 -5  8
2  4  1 -2  0

In [47]:
df.subtract(df['R'], axis=0)        # axis=0이므로 행 방향으로 R 원소 값들을 빼준다.

Q  R  S  T
0 -4  0 -2 -7
1 -5  0 -7  1
2 -1  0 -5 -8

In [48]:
halfrow = df.iloc[0, ::2]          # 첫 번째 행을 2칸 간격으로 추출.
halfrow

Q    4
S    6
Name: 0, dtype: int64

In [49]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN -5.0 NaN
2  4.0 NaN -2.0 NaN

# Missing Data

In [4]:
vals1 = np.array([1, None, 3, 4])

In [5]:
vals1

array([1, None, 3, 4], dtype=object)

In [6]:
for dtype in ['object', 'int']: 
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum() 
    print()

dtype = object
62.8 ms ± 721 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
1.79 ms ± 29.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



In [7]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [10]:
1+np.nan

nan

In [12]:
vals2.sum(),vals2.min(),vals2.max()

(nan, nan, nan)

In [13]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)     #nansum, nanmin 으로 써주면 nan값 무시.

(8.0, 1.0, 4.0)

In [14]:
# Nan, None
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [16]:
x=pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [17]:
x[0]=None        # integer에서 float(실수)로 바뀜.
x

0    NaN
1    1.0
dtype: float64

In [18]:
data=pd.Series([1,np.nan,'hello',None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [19]:
data[data.notnull()]      # null 아닌 것들만 반환.

0        1
2    hello
dtype: object

In [20]:
data.dropna()

0        1
2    hello
dtype: object

In [22]:
df=pd.DataFrame([[1, np.nan, 2],[2,3,5],[np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [23]:
df.dropna()     # default : 행

0    1  2
1  2.0  3.0  5

In [24]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [25]:
df[3]=np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [26]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [27]:
df.dropna(axis='rows', thresh=3)     # null 아닌 값이 최소 3개가 되도록.

0    1  2   3
1  2.0  3.0  5 NaN

In [28]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [29]:
df.fillna(method='ffill', axis=1)      #열 방향으로 앞의 값을 채워넣는다.

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [30]:
#Multi Indexing
#Bad way
index = [('California', 2000), ('California', 2010),
                    ('New York', 2000), ('New York', 2010),
                    ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
                          18976457, 19378102,
                          20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [31]:
pop[('California', 2010):('Texas', 2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [32]:
pop[[i for i in pop.index if i[1] == 2010]]    #index의 두번째 값이 2010인 값만 추출.

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [33]:
#Better way
index = pd.MultiIndex.from_tuples(index)      #지역마다 2개의 index가짐.
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [34]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [35]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [36]:
pop_df = pop.unstack()       
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [37]:
pop_df.stack()         # multi_indexing 효과.

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [39]:
df = pd.DataFrame(np.random.rand(4, 2), 
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.934957  0.017824
  2  0.646174  0.193125
b 1  0.783986  0.512681
  2  0.488418  0.284724

In [40]:
data = {('California', 2000): 33871648,
                    ('California', 2010): 37253956,
                    ('Texas', 2000): 20851820,
                    ('Texas', 2010): 25145561,
                    ('New York', 2000): 18976457,
                    ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [41]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [42]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.611782
      2      0.846168
c     1      0.870067
      2      0.969141
b     1      0.893821
      2      0.817005
dtype: float64

In [54]:
pop
pop.index.names = ['state', 'year']

In [55]:
pop.unstack(level=0)       # column에 첫번째 index level이 들어감.

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [56]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [46]:
pop.unstack().stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [58]:
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [59]:
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [60]:

index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                       names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])


In [61]:
index

MultiIndex(levels=[[2013, 2014], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['year', 'visit'])

In [62]:
columns

MultiIndex(levels=[['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]],
           names=['subject', 'type'])

In [64]:
data = np.round(np.random.randn(4, 6), 1)
data

array([[-0. ,  0.4, -0.1,  0.4,  0.1,  0.8],
       [-0.7, -0.7, -0.2, -0.5, -1.3,  1.1],
       [-1.5, -1. ,  0.6,  0.2,  2.4, -1.1],
       [-0.9, -0.9,  1.7, -0.3, -0.1, -1. ]])

In [65]:
data[:, ::2] *= 10     #모든 행에 대해서, 3번재 열까지만 10을 곱해준다.
data

array([[ -0. ,   0.4,  -1. ,   0.4,   1. ,   0.8],
       [ -7. ,  -0.7,  -2. ,  -0.5, -13. ,   1.1],
       [-15. ,  -1. ,   6. ,   0.2,  24. ,  -1.1],
       [ -9. ,  -0.9,  17. ,  -0.3,  -1. ,  -1. ]])

In [66]:
data += 37
data

array([[37. , 37.4, 36. , 37.4, 38. , 37.8],
       [30. , 36.3, 35. , 36.5, 24. , 38.1],
       [22. , 36. , 43. , 37.2, 61. , 35.9],
       [28. , 36.1, 54. , 36.7, 36. , 36. ]])

In [67]:
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      37.0  37.4  36.0  37.4  38.0  37.8
     2      30.0  36.3  35.0  36.5  24.0  38.1
2014 1      22.0  36.0  43.0  37.2  61.0  35.9
     2      28.0  36.1  54.0  36.7  36.0  36.0

In [68]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      36.0  37.4
     2      35.0  36.5
2014 1      43.0  37.2
     2      54.0  36.7

# p.140
# Data Aggregations on Multi-Indices


In [70]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      37.0  37.4  36.0  37.4  38.0  37.8
     2      30.0  36.3  35.0  36.5  24.0  38.1
2014 1      22.0  36.0  43.0  37.2  61.0  35.9
     2      28.0  36.1  54.0  36.7  36.0  36.0

In [71]:
data_mean = health_data.mean(level='year')    #연도별로 2번 visit의 평균을 구함.
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     33.5  36.85  35.5  36.95  31.0  37.95
2014     25.0  36.05  48.5  36.95  48.5  35.95

In [72]:
data_mean.mean(axis=1, level='type')      # type에 해당하는 열 별로 평균을 구함.

#모든 방문에 대해서 heart rate, temperature 의 평균을 구할 수 있다.

type         HR       Temp
year                      
2013  33.333333  37.250000
2014  40.666667  36.316667

# Combining Datasets: Concat and Append

In [73]:
import pandas as pd 
import numpy as np

In [74]:
# Dataframe 만드는 함수 정의.
def make_df(cols, ind): 
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]     #cols+ind 인 string 만듦.
            for c in cols}
    return pd.DataFrame(data, ind) 

# 열:cols, index=ind 로 가지는 데이터 프레임 만든다.

In [75]:
# example DataFrame
make_df('ABC', range(3))      #columns=(A,B,C), index=(0,1,2)

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

# Recall: Concatenation of NumPy Arrays

In [76]:
x=[1,2,3] 
y=[4,5,6] 
z=[7,8,9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=1)       # 열 방향으로 연속으로 합쳐줌.

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [80]:
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=0)       # 행 방향.

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

# Simple Concatenation with pd.concat

In [82]:
# pd.concat의 형태

#pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
#              keys=None, levels=None, names=None, verify_integrity=False,
#              copy=True)

In [83]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])


In [84]:
ser1

1    A
2    B
3    C
dtype: object

In [85]:
ser2

4    D
5    E
6    F
dtype: object

In [86]:
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [87]:
# data frame에서도 할 수 있다.
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])

In [88]:
df1

A   B
1  A1  B1
2  A2  B2

In [89]:
df2

A   B
3  A3  B3
4  A4  B4

In [90]:
pd.concat([df1,df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [92]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
print(df3); print(df4)
print(pd.concat([df3, df4], axis='columns'))    #열 방향으로 합쳐줌.

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


# Duplicate indices

In [93]:
#pd.concat은 index가 똑같아도 중복되지 않게 합쳐준다.

x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])

In [96]:
print(x); print(y)

    A   B
0  A0  B0
1  A1  B1
    A   B
2  A2  B2
3  A3  B3


In [97]:
y.index=x.index           ## make duplicate indices!

In [98]:
print(x); print(y)        # index를 똑같게 만들었다.

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3


In [100]:
pd.concat([x, y])          # index가 같으므로 데이터 추출 시 구분이 불가능할 수 있다.

A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [101]:
np.concatenate([x, y])

array([['A0', 'B0'],
       ['A1', 'B1'],
       ['A2', 'B2'],
       ['A3', 'B3']], dtype=object)

In [102]:
# Catching the repeats as an error.

try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e: 
    print("ValueError:", e)

ValueError: Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


In [103]:
## Ignoring the index.

print(x); print(y); print(pd.concat([x, y], ignore_index=True))

# 기존의 index를 무시하고 새롭게 부여.

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


In [104]:
## Adding MultiIndex keys.

print(x); print(y); print(pd.concat([x, y], keys=['x', 'y']))

# 인덱스를 무시하는 방법 외에 중복된 인덱스를 구분하기 위하여 keys값을 부여.
# x, y 데이터 프레임이 구분 가능해짐.
# multiply indexed Data Frame이 됨.

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3


In [108]:
## Concatenation with joins
# 열의 이름이 같지 않을 때 joins를 이용하여 concatenation 하는 법

df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print(df5); print(df6); print(pd.concat([df5, df6]))

# default로 sorting되었다는 것을 알려주는 warnings.

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


/Users/jinyoungkim/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  


In [109]:
print(df5); print(df6); print(pd.concat([df5, df6], join='inner'))

# (join='outer')가 default값.
# 겹치는 원소 값들만 연속으로 합쳐서 보여줌.

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [110]:
print(df5); print(df6);
print(pd.concat([df5, df6], join_axes=[df5.columns]))

# 두 데이터프레임에 존재하는 B,C 열 데이터만 보여주지 않고,
# df5 데이터 프레임의 열 이름에 해당하는 원소값들을 연속으로 보여준다.
# 빈 값은 NaN으로 채움.

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4


# Combining Datasets: Merge and Join

In [111]:
# Relational Algebra
# 관계 대수(relational algebra)는 원하는 결과를 얻기 위해 데이터의 처리 과정을 순서대로 기술하는 절차 언어,
# one-to-one, many-to-one, many-to-many joins를 처리 : pd.merge()

In [113]:
## One-to-one joins
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                        'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
'hire_date': [2004, 2008, 2012, 2014]})

# index를 따로 주지 않고 데이터 프레임 생성.

In [114]:
print(df1); print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [115]:
df3 = pd.merge(df1, df2)       #두개의 데이터프레임을 하나의 데이터프레임으로 병합.
df3

# employee 이름이 겹치므로, 각 이름에 해당하는 두 개의 데이터를 병합.
# 각각의 데이터가 일대일 매칭이 되므로 one-to-one merge.
# 기본적으로 pd.merge()에서 index는 신경쓰지 않음.

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [116]:
## Many-to-one joins
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                               'supervisor': ['Carly', 'Guido', 'Steve']})


# 3개의 열에 새로운 열을 1개 병합.
# 일대일 매칭이 되지 않고, 공통으로 존재하는 열 group에서 첫번째 array에 duplicate가 존재.
# 따라서 many-to-one 병합.

In [117]:
print(df3); print(df4)

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve


In [118]:
pd.merge(df3, df4)

# df4에는 Lisa에 해당하는 데이터 값이 없다.
# 앞에 있는 index=1의 데이터를 Duplicate.
# Engineering, Guido 값을 Lisa에게 한번 더 반복한다.

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [119]:
## Many-to-many joins

df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                                         'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                                      'spreadsheets', 'organization']})

df5

group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

In [120]:
df1

#병합 기준인 group열을 볼 때, 두 array모두 duplicate가 존재하므로  many-to-many 병합.

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [121]:
pd.merge(df1, df5)

employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

# Specification of the Merge Key

In [122]:
# on keyword
# 병합하는 key-column을 명시할 수 있다.

print(df1); print(df2); print(pd.merge(df1, df2, on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [127]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'salary': [70000, 80000, 120000, 90000]}) 

In [128]:
df3

name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [129]:
# left_on and right_on keywords
# 열 이름을 다르게 지정하여 병합하고 싶을 때.

pd.merge(df1, df3, left_on="employee", right_on="name")

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [130]:
# 쓸데없이 중복되는 열 버리기.

pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [133]:
# left_index and right_index keywords
# 열 방향 대신 행 방향으로 병합.

df1a = df1.set_index('employee') 
df2a = df2.set_index('employee') 
print(df1a); print(df2a)

#열에 해당하던 employee를 index로 바꿈.

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014


In [134]:
pd.merge(df1a, df2a, left_index=True, right_index=True)

#index를 기준으로 병합.

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [136]:
df1a.join(df2a)        # 똑같은 결과.


group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [137]:
print(df1a); print(df3);
print(pd.merge(df1a, df3, left_index=True, right_on='name'))

# index인 employee와, column인 name 을 기준으로 병합.

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000
         group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000


# Specifying Set Arithmetic for Joins

In [138]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                                'food': ['fish', 'beans', 'bread']},
                               columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                                'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])

In [140]:
df6

name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

In [141]:
df7

name drink
0    Mary  wine
1  Joseph  beer

In [142]:
pd.merge(df6, df7)

# 겹치는 Mary에 대해서 병합.

name   food drink
0  Mary  bread  wine

In [143]:
pd.merge(df6, df7, how='inner')      # default=inner

name   food drink
0  Mary  bread  wine

In [144]:
pd.merge(df6, df7, how='outer')

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [146]:
print(df6); print(df7); print(pd.merge(df6, df7, how='left'))

#df6 의 열 기준으로 병합.

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine


In [147]:
print(df6); print(df7); print(pd.merge(df6, df7, how='right'))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer


# Overlapping Column Names: The suffixes Keyword

In [149]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                                'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})

In [150]:
df8

name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

In [151]:
df9

name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

In [152]:
pd.merge(df8, df9, on="name")     

# 각 name에 해당하는 rank값이 다르므로 구분하기 위해 rank_x,y를 생성.

name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [153]:
pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])

# rank_x,y 대신 원하는 이름 지정 가능.

name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

# Example: US States Data

In [160]:
# Following are shell commands to download the data
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv
    
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57935  100 57935    0     0   231k      0 --:--:-- --:--:-- --:--:--  231k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   835  100   835    0     0   5422      0 --:--:-- --:--:-- --:--:--  5457
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   872  100   872    0     0   5253      0 --:--:-- --:--:-- --:--:--  5253


In [161]:
print(pop.head()); print(areas.head()); print(abbrevs.head())

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0
        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707
        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA


In [181]:
## many-to-one merge

# merge based on the state/region column of pop, 
# and the abbreviation column of abbrevs

merged = pd.merge(pop, abbrevs, how='outer',
                  left_on='state/region', right_on='abbreviation')
merged.head()

state/region     ages  year  population    state abbreviation
0           AL  under18  2012   1117489.0  Alabama           AL
1           AL    total  2012   4817528.0  Alabama           AL
2           AL  under18  2010   1130966.0  Alabama           AL
3           AL    total  2010   4785570.0  Alabama           AL
4           AL  under18  2011   1125763.0  Alabama           AL

In [170]:
merged = merged.drop('abbreviation', 1)    # drop duplicate info
    

# 겹치는 열인 state/region과 abbreviation 기준으롭 병합한 후,
# 중복되는 열을 삭제한다.

In [171]:
merged.head()

state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

In [172]:
merged.isnull().any()          # 행별로 null값이 있는지 없는지 알려줌.

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [182]:
merged['population'].head()

0    1117489.0
1    4817528.0
2    1130966.0
3    4785570.0
4    1125763.0
Name: population, dtype: float64

In [174]:
merged[merged['population'].isnull()].head()

# population열 값 중 null값이 존재하는 해당 행의 데이터만 뽑아서 보여준다.

state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN

In [175]:
merged.loc[merged['state'].isnull(), 'state/region'].unique()

# state값이 null인 데이터들의 state/region 값을 unique하게 추출.
# name에는 있으나 abbreviation에는 없는 state/region 값이 추출됨.

array(['PR', 'USA'], dtype=object)

In [176]:
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

# state/region값이 PR,USA 이면 
# 각각의 state에 'Puerto Rico', 'United States' 써준다.

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [178]:
areas.head()

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [179]:
final = pd.merge(merged, areas, on='state', how='left')   #state기준으로 병합.
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [180]:
# check for nulls

final.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool

In [183]:
final['state'][final['area (sq. mi)'].isnull()].unique()

# area(sq. mi)값이 null인 state를 추출.

array(['United States'], dtype=object)

In [184]:
final.dropna(inplace=True)
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [185]:
# query() function 쓰기 위한 패키지 설치.
import numexpr

In [197]:
data2010 = final.query("year == 2010 & ages == 'total'")
data2010.head()

# final 에서 year=2010, ages=total인 값만 추출.

state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

In [198]:
# rein‐dexing our data on the state
# compute population density 

data2010.set_index('state', inplace=True)

In [199]:
data2010.head()       #index가 state로 새로 바뀜.

state/region   ages  year  population  area (sq. mi)
state                                                          
Alabama              AL  total  2010   4785570.0        52423.0
Alaska               AK  total  2010    713868.0       656425.0
Arizona              AZ  total  2010   6408790.0       114006.0
Arkansas             AR  total  2010   2922280.0        53182.0
California           CA  total  2010  37333601.0       163707.0

In [201]:
density = data2010['population'] / data2010['area (sq. mi)']

In [202]:
density.sort_values(ascending=False, inplace=True)     # 내림차순.
density.head()

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
dtype: float64

In [203]:
density.tail()        # 맨 끝 부분만 보여줌.

state
South Dakota    10.583512
North Dakota     9.537565
Montana          6.736171
Wyoming          5.768079
Alaska           1.087509
dtype: float64

# Aggregation and Grouping

In [204]:
## Planets Data

import seaborn as sns
planets = sns.load_dataset('planets') 
planets.shape

(1035, 6)

In [205]:
planets.head()       # 2014년 까지의 데이터.

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [206]:
## Simple Aggregation in Pandas

rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [207]:
ser.sum()

2.811925491708157

In [208]:
ser.mean()

0.5623850983416314

In [209]:
df = pd.DataFrame({'A': rng.rand(5),
                   'B': rng.rand(5)})
df

A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825

In [210]:
df.mean()

A    0.477888
B    0.443420
dtype: float64

In [211]:
df.mean(axis='columns')       # 열 방향으로 평균 구함.

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

In [212]:
## 다시 planets 데이터로 분석.
planets.dropna().describe()

# .mean, .max 등등 기본적인 분석을 describe()로 할 수 있다.
# count() : total number of items
# first(), last() : First and last item
# mad() : mean absolute deviation
## 기본적인 분석으로 부족한 경우 => GroupBy

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

# GroupBy: Split, Apply, Combine

- The split step involves breaking up and grouping a DataFrame depending on the value of the specified key.
- The apply step involves computing some function, usually an aggregate, transformation, or filtering, within the individual groups.
- The combine step merges the results of these operations into an output array.

In [213]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'], 
                   'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [214]:
df.groupby('key')
# dataframe 형태로 만들기 위해서는 aggregation 필요.

In [215]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [216]:
planets.groupby('method')['orbital_period']

In [217]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [218]:
## iteration over groups.

for (method, group) in planets.groupby('method'): 
    print("{0:30s} shape={1}".format(method, group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)


In [219]:
## Dispatch methods.

planets.groupby('method')['year'].describe().unstack()   #기초 분석.

       method                       
count  Astrometry                          2.000000
       Eclipse Timing Variations           9.000000
       Imaging                            38.000000
       Microlensing                       23.000000
       Orbital Brightness Modulation       3.000000
       Pulsar Timing                       5.000000
       Pulsation Timing Variations         1.000000
       Radial Velocity                   553.000000
       Transit                           397.000000
       Transit Timing Variations           4.000000
mean   Astrometry                       2011.500000
       Eclipse Timing Variations        2010.000000
       Imaging                          2009.131579
       Microlensing                     2009.782609
       Orbital Brightness Modulation    2011.666667
       Pulsar Timing                    1998.400000
       Pulsation Timing Variations      2007.000000
       Radial Velocity                  2007.518987
       Transit             